### ISSUE TITLE
Leaf Regeneration

### ISSUE THREAD

**Issue by 63502** [ferreusveritas/DynamicTrees#1]
Sometimes when trees of any kind are growing, some of the leaves will constantly appear, disappear, and reappear at the ends of branches. All you should need to do to observe this behavior is plant a growing tree and grow it to a stage where it has multiple branches.

**Comment by 63502** [comment]
Ok, I guess this mod is abandoned.

Darn. :(

**Comment by ferreusveritas** [comment]
This issue isn't solved yet.  It's a known issue and we may either have to live with it as an artifact of how the growth cellular automata works or dig deeper into the problem to minimize it's effect.  For the most part it should be rather slow and subtle and not a huge problem.  If it's happening rapidly then it's not something I'm aware of as I'm not experiencing it rapidly on my end.

**Comment by Flabort** [comment]
@63502 are you using this with Fast Leaf Decay?

I suspect the rapid flickering of leaves may be due to that?

**Comment by ghost** [comment]
Can anyone report with certainty that this is an interaction issue with Fast Leaf Decay?

**Comment by ferreusveritas** [comment]
I've done a lot of work on leaf block cell automata and may have accidentally fixed this issue.  I haven't seen any sign of it for a long long time.  If nobody is experiencing this issue anymore I'm closing this issue.

**Comment by Miaourt** [comment]
Since nobody seem to have confirmed I can confirm that leaves are re-growing very fast when broke when mods that accelerate leave decaying are installed

**Comment by ghost** [comment]
This should now be fixed in dev.  I cancel the NeighborNotifyEvent if there's an adjacent DynamicLeavesBlock.
