### ISSUE TITLE
Vanilla sapling bug

### ISSUE THREAD

**Issue by Joaquitox** [ferreusveritas/DynamicTrees#395]
I want to plant vanilla trees for a mod that i am using that isn't compatible (TekTopia) but when i make the vanilla sapling and place it in the floor it is there for a second and then ut changes to a dynamic tree sapling, it would be great if you help me cuz without vanilla trees the tektopia mod is literally useless

*Get a vanilla tree sapling
*Place it in the floor

I am not using optifine

i only put dynamic trees in the mod order and it still bugs

**Comment by ferreusveritas** [comment]
What does your Dynamic Trees config file look like?  Make sure the replaceVanillaSapling is set to false
```
vanilla {
    # Right clicking with a vanilla sapling places a dynamic sapling instead. [default: false]
    B:replaceVanillaSapling=false
}
```
