### ISSUE TITLE
[Suggestion] Mod Integration with Passable Leaves

### ISSUE THREAD

**Issue by Tetrajak** [ferreusveritas/DynamicTrees#5]
It'd be great if the mod had integration with the Passable Leaves mod, so that when both mods are present in a pack there is consistent behaviour for all leaf type blocks.

**Comment by ferreusveritas** [comment]
I'm not against this suggestion but it's pretty low priority at the moment. Depends a great deal on how many people would benefit from this.

**Comment by Tetrajak** [comment]
All good, I understand. The main benefit is for exploring while riding on horseback; you don't get stopped while exploring a forest, or trying to navigate a hill with trees, when you have Passable Leaves.

**Comment by ghost** [comment]
This feature has been added.
