### ISSUE TITLE
[Suggestion] enable dendrocoil with opencomputers

### ISSUE THREAD

**Issue by LiEyWe** [ferreusveritas/DynamicTrees#7]
As OC is now out for 1.12.1, it would be nice to use the dendrocoil with this mod too.

**Comment by ferreusveritas** [comment]
It would be nice.  I'll put it on the TODO list.
Did you actually use the Dendrocoil?  Nobody has even said anything about it yet.

**Comment by LiEyWe** [comment]
Yeah. atm i mainly use getSoilLife for automating a tree farm with dynamic trees.
btw should growPulse do the same as a potion of swiftness? i put growPulse in a loop, but it seems to not affect the tree. or are there parameters needed?

**Comment by ferreusveritas** [comment]
It should effect the tree growth as long as the rooty dirt block in on top of the Dendrocoil and a tree is planted there.  It will force an age cycle for the entire tree but it doesn't do it evenly.  Although it ages the entire tree(leaves and branches) every pulse, It will only cause a growth event approximately 1 in 8 times.  Even when the rooty dirt block is pulsed each species may react differently.  Some of the slower growing trees will ignore the growth signal more often than the faster growing ones.  But it should definitely grow the tree way faster.  I use it for rapidly growing tree models for worldgen in "growing chambers".  Try doing a side by side comparison with 2 trees (one on a coil and the other natural) and if you don't notice a difference let me know.  You might have found a bug.

**Comment by LiEyWe** [comment]
ahh ok. thanks for the answer. I will compare those and write again.

**Comment by ghost** [comment]
OpenComputers features an adapter that should do the trick nicely.  I haven't tested it myself though.

**Comment by ghost** [comment]
This peripheral is going to be removed from the Dynamic Trees mod and placed into the "Magic Cracker Factory" mod.  Very few people understand what the block is for and even fewer know how to use it.  99% of the players don't use it and that's a good enough reason to remove it from the mod.
