### ISSUE TITLE
[Suggestion] Rooty dirt quark grass color compatibility

### ISSUE THREAD

**Issue by LiEyWe** [ferreusveritas/DynamicTrees#8]
When using quark, the rooty dirt has the vanilla grass color.
https://imgur.com/a/ZFSeK

**Comment by ferreusveritas** [comment]
It has the wrong color because quark broke it with it's "greener grass" option.  Turn the option off or deal with the color being wrong.  Not my problem.

**Comment by ghost** [comment]
Quark is hugely popular and has some neat features.  I'm relenting on my decision not to support it.  I'll see what it takes to fix this minor issue.

**Comment by ghost** [comment]
Quark greener grass compatibility has been added in the latest code push.
